config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles

  resources :groups do
    collection do
      get 'markers'
      post 'updatemarkers'
      post 'deletemarker'
      post 'updatemarkerposition'
    end
    resources :invites do
      collection do
        post 'acceptgroup'
        post 'denygroup'
      end
    end
  end

  resources :markers
  resources :members
  resources :staticpages

  resources :invites
  root 'staticpages#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  validates :user, presence: true

  mount_uploader :avatar_url, ImageUploader

  validates_processing_of :avatar_url
  validate :avatar_url_size_validation

  private

  def avatar_url_size_validation
    errors[:avatar_url] << "should be less than 500KB" if avatar_url.size > 0.5.megabytes
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authorize_user, only: [:show, :edit, :update]

  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
    @invites = Invite.where(user: current_user).where(accepted: false)
    @user = @profile.user
  end

  def edit
    @profile = Profile.find(params[:id])
    if current_user.email == @profile.user.email
      render :edit
    else
      redirect_to root_path
    end
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      flash[:notice] = "Profile updated!"
      redirect_to profile_path(@profile)
    else
      flash[:error] = "Did not manage to update profile. #{@profile.errors.full_messages.join(', ')}."
      render :edit
    end
  end

  private

  def profile_params
    params.require(:profile).permit(
      :location,
      :about,
      :avatar_url,
      :remove_avatar_url
    )
  end

  def authorize_user
    if !user_signed_in?
      redirect_to root_path
    end
  end
end

app/views/profiles/edit.html.erb
<div class="editprofile">Edit Profile</div>

<%= form_for @profile do |f| %>

  <%= f.label :location, "Current location" %>
  <%= f.text_field :location %>

  <%= f.label :about, "About me" %>
  <%= f.text_area :about %>

  <%= f.label :avatar_url, "Upload Image" %>
  <%= f.file_field :avatar_url %>
  <br />
  <% if f.object.avatar_url? %>
    <%= image_tag f.object.avatar_url.thumb.url %>
      <br />
    <div class="remove_avatar_stuff">
    <%= f.label :remove_avatar_url %>
    <%= f.check_box :remove_avatar_url %>
    </div>
  <% end %>
  <br />


  <%= f.submit "Update Profile", class:'button', id:"updateprofbutton" %>
<% end %>

app/views/profiles/show.html.erb
<div class="Profiletitle">
  Your Profile!
</div>

</div>

<div class="information">
  <div class="row">Name: <%= current_user.name %></div>

  <% if @profile.about.nil? != true %>
    <div class="row">About: <%= @profile.about %></div>
  <% end %>

  <% if @profile.location.nil? != true %>
    <div class="row">Current Location: <%= @profile.location %></div>
  <% end %>

  <% if @profile.avatar_url.nil? != true %>
    <%= image_tag "#{@profile.avatar_url.thumb.url}" %>
  <% end %>
</div>

<%= link_to "Edit Profile", edit_profile_path, class:"button" %>

<% if !@invites.empty? %>
  <div id="infobutton2" class="button" data-open="exampleModal2">View Your Invites!</div>
<% end %>

<div class="reveal invitesmagic" id="exampleModal2" data-reveal>
  <div class="invitesbox">
    <% @invites.each do |invite| %>
      <div class="groupname">
        You were invited to join <%= invite.group.name %>
      </div>
      <div class="showMembers">
        <h5>Members</h5>
        <% invite.group.members.each do |member| %>
          <%= member.user.name %><br>
        <% end %>
        <br>
      </div>
      <div class="acceptrejectGroup">
        <%= button_to "Accept Invitation", acceptgroup_group_invites_path(invite.group), class: 'button' %>
        <%= button_to "Reject Invitation", denygroup_group_invites_path(invite.group), class: 'button' %>
      </div>
    <% end %>
  </div>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>