config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles

  resources :groups do
    collection do
      get 'markers'
      post 'updatemarkers'
      post 'deletemarker'
      post 'updatemarkerposition'
    end
    resources :invites do
      collection do
        post 'acceptgroup'
        post 'denygroup'
      end
    end
  end

  resources :markers
  resources :members
  resources :staticpages

  resources :invites
  root 'staticpages#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :members, dependent: :destroy
  has_many :users, through: :members
  has_many :invites

  validates :name, presence: true
  validates :city, presence: true
  validates :country, presence: true

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    "#{city}, #{state}, #{country}"
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @relevant_groups = []
    @groups = Group.all
    @groups.each do |group|
      group.members.each do |member|
        if member.user == current_user
          @relevant_groups << member.group
        end
      end
    end
  end

  def show
    @group = Group.find(params[:id])
    @members = @group.members.map { |member| member.user }
    @invites = Invite.where(group: @group)
    @invited = @invites.map { |invite| invite.user }
    @user_selects = User.all - @members - @invited
    @invite = Invite.new
    if member?(@group) == true
      render :show
    else
      flash[:notice] = "You do not have permission to view these details"
      redirect_to "/"
    end
  end

  def markers
    @id = params[:group_id]
    @group = Group.find(@id)
    @members = @group.members
    # @markers = Marker.all
    @markers = Marker.where(member: @members)
    render json: @markers
  end

  def updatemarkers
    @marker =  Marker.find(params[:id])
    @marker.title = params[:title]
    @marker.description = params[:description]
    @marker.save
    render json: @marker
  end

  def deletemarker
    @marker = Marker.find(params[:id])
    @marker.destroy
    render json: "Marker removed!"
  end

  def updatemarkerposition
    @marker = Marker.find(params[:id])
    @marker.longitude = params[:longitude]
    @marker.latitude = params[:latitude]
    @marker.save
    render json: @marker
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @member = Member.new(user: current_user, group: @group, owner: true)
    if @group.save && @member.save
      flash[:notice] = "Group added successfully!"
      redirect_to group_path(@group)
    else
      flash[:error] = "Group not added successfully! #{@group.errors.full_messages.join ', '}."
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
    if member?(@group) == true
      render :edit
    else
      flash[:notice] = "You do not have permission to edit these details"
      redirect_to "/"
    end
  end

  def update
    @group = Group.find(params[:id])

    if owner?(@group) == true
      if @group.update(group_params)
        flash[:notice] = "You just updated your Group Info!"
        redirect_to group_path(@group)
      else
        flash[:error] = "Did not update Group. #{@profile.errors.full_messages.join(', ')}."
        render :edit
      end
    else
      flash[:notice] = "You do not have permission to change this group"
      redirect_to "/"
    end
  end

  def destroy
    @group = Group.find(params[:id])

    if owner?(@group) == true
      if @group.destroy
        flash[:notice] = "Group Deleted Successfully"
        redirect_to groups_path
      else
        flash[:notice] = "You do not have permission to delete this group"
        redirect_to group_path(@group)
      end
    else
      flash[:notice] = "You do not have permission to delete this group"
      redirect_to group_path(@group)
    end
  end

  private

  def group_params
    params.require(:group).permit(
      :name,
      :city,
      :state,
      :country
    )
  end

  def member?(group)
    group.members.each do |member|
      if member.user == current_user
        return true
      end
    end
  end

  def owner?(group)
    group.members.each do |member|
      if member.user == current_user && member.owner == true
        return true
      end
    end
  end
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>

  <%= f.label :city, "City" %>
  <%= f.text_field :city %>

  <%= f.label :state, "State" %>
  <%= f.text_field :state %>

  <%= f.label :country, "Country" %>
  <%= f.text_area :country %>

  <%= f.submit "Submit", class:"button", id:"updatebuttonspecial" %>
<% end %>

app/views/groups/edit.html.erb
<div class="updategrouptitle">Update your Group</div>

<%= render "form" %>

app/views/groups/index.html.erb
<html id="group-totals">

  <div class="group-index-page">
    Your Groups!
  </div>

  <div class="group-content">
    <% @relevant_groups.each do |group| %>
      <div class="small-12 medium-4 columns row-padding">
        <div class="groupies">
          <%= link_to "#{group.name}", group_path(group) %></br>
          <%= group.city %>
        </div>
      </div>
    <% end %>
  </div>

</html>

app/views/groups/new.html.erb
<div class="groupform">

  <div class="createyourgroup">Create Your Group!</div>

  <div class="creategroupmessage">
    Please fill out all fields in order to create your group.
  </div>

  <%= render "form" %>

</div>

app/views/groups/show.html.erb
<html id="group-individuals">

<div class="reveal groupmagic" id="exampleModal1" data-reveal>
  <h1><%= @group.name %></h1>
  <p class="lead"><%= @group.city %></p>
  <h5>Members:</h5>
  <% @group.members.each do |member| %>
    <p><%= member.user.name %></p>
  <% end %>
  <%= render '/invites/form'  %>
  <p><%= button_to "Delete #{@group.name}", group_path(@group), class:"button", method:"delete" %></p>
  <p><%= link_to "Edit #{@group.name}", edit_group_path(@group), class:"button" %></p>
  <button class="close-button" data-close aria-label="Close modal" type="button">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<div id="infobutton" class="button" data-open="exampleModal1">View Group Info</div>

<span id="data-group-id" data-group-id= "<%= @group.id %>" ></span>
<span id="data-group-latitude" data-group-latitude= "<%= @group.latitude %>" ></span>
<span id="data-group-longitude" data-group-longitude= "<%= @group.longitude %>" ></span>

  <input id="pac-input" class="controls" type="text" placeholder="Search Box">
  <div id="googleMap" style="width:80%;height:91%;"></div>
  <div id="marker-sidebar" style="overflow:scroll; width:20%;height:91%"></div>
  <div class="your point"></div>

</html>