config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :profiles

  resources :groups do
    collection do
      get 'markers'
      post 'updatemarkers'
      post 'deletemarker'
      post 'updatemarkerposition'
    end
    resources :invites do
      collection do
        post 'acceptgroup'
        post 'denygroup'
      end
    end
  end

  resources :markers
  resources :members
  resources :staticpages

  resources :invites
  root 'staticpages#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://maps.googleapis.com/maps/api/js?v=3.5&key=<%= ENV['MY_MAPS'] %>&libraries=places&callback=initMap"></script>
    <link href='https://fonts.googleapis.com/css?family=Leckerli+One' rel='stylesheet' type='text/css'>

    <title><%= content_for?(:title) ? yield(:title) : "MapShare" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="top-bar">

      <div class="top-bar-left">
        <%= link_to image_tag("cityscout-white.png"), root_path, class: 'logo'%>
      </div>

      <div class="top-bar-right">
        <ul class="dropdown menu happiness" data-dropdown-menu>
          <li>
            <a href="#">Your Account</a>
              <ul class="menu">
                <li><%= link_to "Sign up", new_user_registration_path if !current_user %></li>
                <li><%= link_to "Sign in", new_user_session_path if !current_user%></li>
                <li><%= link_to "Sign out", destroy_user_session_path, method: :delete if current_user%></li>
                <li><%= link_to "Edit registration", edit_user_registration_path if current_user %></li>
              </ul>
          </li>
          <% if current_user %>
            <li>
              <a href="#">Your Profile</a>
                <ul class="menu">
                  <li><%= link_to "Profile", profile_path(current_user.profile) %></li>
                </ul>
            </li>
            <li>
              <a href="#">Your Groups</a>
                <ul class="menu">
                  <li><%= link_to "New Group", new_group_path %></li>
                  <li><%= link_to "See your Groups", groups_path %></li>
                </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

     <div class="notices small-12 columns" id="flash-notices-non-js">
       <% flash.each do |name, msg| %>
         <% if msg.is_a?(String) %>
           <%= content_tag :div, msg, :class => "flash_#{name}" %>
           <!-- <a class="close" href="#">x</a> -->
         <% end %>
       <% end %>
     </div>

    <%= yield %>

    <%= javascript_include_tag "application" %>
  </body>
</html>